project:
  type: website
  output-dir: _site

website:
  title: "Herdr cache-hit"
  site-url: "https://www.ekotov.pro/herdr-cache-hit/"
  repo-url: "https://github.com/e-kotov/herdr-cache-hit"
  open-graph: true

format:
  closeread-html:
    theme: default
    css: styles.css
    remove-header-space: true
    toc: false
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@800;900&display=swap" rel="stylesheet">
        <!-- counter.dev analytics -->
        <script data-goatcounter="https://jukadipos.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
        <!-- counter.dev analytics -->
        <script src="https://cdn.counter.dev/script.js" data-id="7e3e8d31-9a84-48b0-a678-a00715236a90" data-utcoffset="1"></script>
        <script>
         (function(h,o,t,j,a,r){
             h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
             h._hjSettings={hjid:3578286,hjsv:6};
             a=o.getElementsByTagName('head')[0];
             r=o.createElement('script');r.async=1;
             r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
             a.appendChild(r);
         })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
        </script>
    cr-style:
      narrative-background-color-sidebar: "#f7f2ed"
      narrative-text-color-sidebar: "#241835"
      section-background-color: "#eee8e3"
